version: '3'

networks:
  mynet:

services:
  jboss-jbpm:
    image: jboss/jbpm-server-full
    ports:
      - "8080:8080"
    networks:
      - mynet
    container_name: jboss-jbpm
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/db
      DB_USER: adm
      DB_PASSWORD: 112233
    depends_on:
      - postgres

  nginx:
    image: nginx
    networks:
      - mynet
    container_name: nginx
    ports:
      - "80:80"
   # links:
   #   - jboss-jbpm
   #   - grafana
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - jboss-jbpm
      - grafana

  postgres:
    image: postgres
    networks:
      - mynet
    container_name: postgres
    environment:
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: 112233
      POSTGRES_DB: db

  prometheus:
    image: prom/prometheus
    networks:
      - mynet
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - node-exporter

  grafana:
    image: grafana/grafana
    networks:
      - mynet
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=112233
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
      - ./grafana-dashboards:/etc/grafana/provisioning/dashboards
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml

  node-exporter:
    image: prom/node-exporter
    networks:
      - mynet
    container_name: node-exporter
    ports:
      - "9100:9100"

